@component('elements.widgets.modal')
    @slot('classH','secondary')
    @slot('id','filters')
    @slot('title','Opciones')
    @slot('close',true)
    @slot('size','modal-md')
    @slot('body')
        @include('administracion.registropagos.form.modal.fields')
    @endslot
@endcomponent
