<?php

namespace App\Http\Livewire\Administracion\Bienestar;

trait StudentRecordTrait
{
    protected $rules = [
        // 'student_record.estudiant_id' => 'required|integer',
        'student_record.coexistence' => 'nullable|string',
        'student_record.status_transport_private_vehicle' => 'boolean|nullable',
        'student_record.status_transport_public_vehicle' => 'boolean|nullable',
        'student_record.status_transport_walking' => 'boolean|nullable',
        'student_record.status_transport_other' => 'boolean|nullable',
        'student_record.transport_other' => 'string|nullable',
        'student_record.status_vaccination_schedule' => 'boolean|nullable',
        'student_record.status_sports_potential' => 'boolean|nullable',
        'student_record.sports_potential' => 'string|nullable',
        'student_record.place_where_he_practices' => 'nullable|string',
        'student_record.status_illness_cardiovascular' => 'boolean|nullable',
        'student_record.status_illness_cancer' => 'boolean|nullable',
        'student_record.status_illness_lupus' => 'boolean|nullable',
        'student_record.status_illness_diabetes' => 'boolean|nullable',
        'student_record.status_illness_renal_problems' => 'boolean|nullable',
        'student_record.status_illness_overweight' => 'boolean|nullable',
        'student_record.status_illness_other' => 'boolean|nullable',
        'student_record.illness_other' => 'string|nullable',
        'student_record.status_conditions_intellectual_disability' => 'nullable|boolean',
        'student_record.status_conditions_motor_disability' => 'nullable|boolean',
        'student_record.status_conditions_visual_disability' => 'nullable|boolean',
        'student_record.status_conditions_hearing_impairment' => 'nullable|boolean',
        'student_record.status_conditions_outstanding_attitudes' => 'nullable|boolean',
        'student_record.status_conditions_autism' => 'nullable|boolean',
        'student_record.status_conditions_other' => 'nullable|boolean',
        'student_record.conditions_other' => 'string|nullable',
        'student_record.status_treated_by_specialist' => 'nullable|boolean',
        'student_record.specialist' => 'string|nullable',
        'student_record.status_take_medication' => 'nullable|boolean',
        'student_record.medication' => 'string|nullable',
        'student_record.mother_name' => 'string|nullable',
        'student_record.mother_lastname' => 'string|nullable',
        'student_record.mother_ci' => 'string|nullable',
        'student_record.mother_profession' => 'string|nullable',
        'student_record.mother_phones' => 'string|nullable',
        'student_record.mother_address' => 'string|nullable',
        'student_record.father_name' => 'string|nullable',
        'student_record.father_lastname' => 'string|nullable',
        'student_record.father_ci' => 'string|nullable',
        'student_record.father_profession' => 'string|nullable',
        'student_record.father_phones' => 'string|nullable',
        'student_record.father_address' => 'string|nullable',
    ];

    protected function validationAttributes()
    {
        return [
            // 'student_record.estudiant_id' => $this->list_comment['estudiant_id'],
            'student_record.coexistence' => $this->list_comment['coexistence'],
            'student_record.status_transport_private_vehicle' => $this->list_comment['status_transport_private_vehicle'],
            'student_record.status_transport_public_vehicle' => $this->list_comment['status_transport_public_vehicle'],
            'student_record.status_transport_walking' => $this->list_comment['status_transport_walking'],
            'student_record.status_transport_other' => $this->list_comment['status_transport_other'],
            'student_record.transport_other' => $this->list_comment['transport_other'],
            'student_record.status_vaccination_schedule' => $this->list_comment['status_vaccination_schedule'],
            'student_record.status_sports_potential' => $this->list_comment['status_sports_potential'],
            'student_record.sports_potential' => $this->list_comment['sports_potential'],
            'student_record.place_where_he_practices' => $this->list_comment['place_where_he_practices'],
            'student_record.status_illness_cardiovascular' => $this->list_comment['status_illness_cardiovascular'],
            'student_record.status_illness_cancer' => $this->list_comment['status_illness_cancer'],
            'student_record.status_illness_lupus' => $this->list_comment['status_illness_lupus'],
            'student_record.status_illness_diabetes' => $this->list_comment['status_illness_diabetes'],
            'student_record.status_illness_renal_problems' => $this->list_comment['status_illness_renal_problems'],
            'student_record.status_illness_overweight' => $this->list_comment['status_illness_overweight'],
            'student_record.status_illness_other' => $this->list_comment['status_illness_other'],
            'student_record.illness_other' => $this->list_comment['illness_other'],
            'student_record.status_conditions_intellectual_disability' => $this->list_comment['status_conditions_intellectual_disability'],
            'student_record.status_conditions_motor_disability' => $this->list_comment['status_conditions_motor_disability'],
            'student_record.status_conditions_visual_disability' => $this->list_comment['status_conditions_visual_disability'],
            'student_record.status_conditions_hearing_impairment' => $this->list_comment['status_conditions_hearing_impairment'],
            'student_record.status_conditions_outstanding_attitudes' => $this->list_comment['status_conditions_outstanding_attitudes'],
            'student_record.status_conditions_autism' => $this->list_comment['status_conditions_autism'],
            'student_record.status_conditions_other' => $this->list_comment['status_conditions_other'],
            'student_record.conditions_other' => $this->list_comment['conditions_other'],
            'student_record.status_treated_by_specialist' => $this->list_comment['status_treated_by_specialist'],
            'student_record.specialist' => $this->list_comment['specialist'],
            'student_record.status_take_medication' => $this->list_comment['status_take_medication'],
            'student_record.medication' => $this->list_comment['medication'],
            'student_record.mother_name' => $this->list_comment['mother_name'],
            'student_record.mother_lastname' => $this->list_comment['mother_lastname'],
            'student_record.mother_ci' => $this->list_comment['mother_ci'],
            'student_record.mother_profession' => $this->list_comment['mother_profession'],
            'student_record.mother_phones' => $this->list_comment['mother_phones'],
            'student_record.mother_address' => $this->list_comment['mother_address'],
            'student_record.father_name' => $this->list_comment['father_name'],
            'student_record.father_lastname' => $this->list_comment['father_lastname'],
            'student_record.father_ci' => $this->list_comment['father_ci'],
            'student_record.father_profession' => $this->list_comment['father_profession'],
            'student_record.father_phones' => $this->list_comment['father_phones'],
            'student_record.father_address' => $this->list_comment['father_address'],
        ];
    }
}

?>