<?php

namespace App\Services\Diagnostic;

use App\Models\app\Instrument\DiagReport;
use App\Models\app\Instrument\DiagReportAiDraft;
use App\Models\app\AI\AiPrompt;
use Illuminate\Support\Facades\Auth;

class AiReportService
{
    public function generateDraft(DiagReport $report, $provider = 'openai', $model = 'gpt-4')
    {
        // 1. Fetch Prompts
        $systemPrompt = AiPrompt::system()->active()->latest('version')->first();
        $userPrompt = AiPrompt::user()->active()->latest('version')->first();

        if (!$systemPrompt || !$userPrompt) {
            throw new \Exception("Missing active system or user prompts.");
        }

        // 2. Build Payload (Mock for now)
        $payload = [
            'student_name' => $report->estudiant->first_name ?? 'Student',
            'results' => [
                'global_precision' => $report->results->precision ?? 0,
            ]
        ];
        $payloadJson = json_encode($payload);
        $inputHash = hash('sha256', $payloadJson);

        // 3. Call LLM (Stub)
        $outputText = $this->callLlmStub($systemPrompt->content, $userPrompt->content, $payloadJson);

        // 4. Store Draft
        return DiagReportAiDraft::create([
            'report_id' => $report->id,
            'llm_provider' => $provider,
            'llm_model' => $model,
            'system_prompt_id' => $systemPrompt->id,
            'user_prompt_id' => $userPrompt->id,
            'prompt_version_label' => "SYS:{$systemPrompt->version} / USR:{$userPrompt->version}",
            'input_hash' => $inputHash,
            'output_text' => $outputText,
            'status' => 'generated',
        ]);
    }

    protected function callLlmStub($system, $user, $payload)
    {
        return "STUB REPORT GENERATED BY AI.\nBased on payload: $payload";
    }
}
